/** Anthropic tool schema — forces valid structured plan output (no freeform JSON). */
export const SUBMIT_REVAMP_PLAN_TOOL = {
  name: "submit_revamp_plan",
  description:
    "Submit the complete cosmetic revamp plan for this room as structured data. Keep every string short.",
  input_schema: {
    type: "object",
    properties: {
      roomAnalysis: { type: "string" },
      primaryTheme: { type: "string" },
      designConcept: { type: "string" },
      alternativeTheme: { type: "string" },
      afterImageBrief: { type: "string" },
      roomStructure: {
        type: "object",
        properties: {
          approximateDimensions: { type: "string" },
          ceilingHeight: { type: "string" },
          cameraAngle: { type: "string" },
          floorType: { type: "string" },
          wallDescription: { type: "string" },
          lightDirection: { type: "string" },
          referencePhotoIndex: { type: "integer" },
          fixtures: {
            type: "array",
            items: {
              type: "object",
              properties: {
                type: { type: "string" },
                position: { type: "string" },
                description: { type: "string" },
              },
              required: ["type", "position", "description"],
            },
          },
          existingFurniture: {
            type: "array",
            items: {
              type: "object",
              properties: {
                item: { type: "string" },
                position: { type: "string" },
                notes: { type: "string" },
              },
              required: ["item", "position", "notes"],
            },
          },
        },
        required: [
          "approximateDimensions",
          "ceilingHeight",
          "cameraAngle",
          "floorType",
          "wallDescription",
          "lightDirection",
          "referencePhotoIndex",
          "fixtures",
          "existingFurniture",
        ],
      },
      visionSummary: { type: "string" },
      designDirection: { type: "string" },
      colorPalette: { type: "array", items: { type: "string" } },
      keyChanges: { type: "array", items: { type: "string" } },
      assumptions: { type: "array", items: { type: "string" } },
      costLineItems: {
        type: "array",
        items: {
          type: "object",
          properties: {
            lineNumber: { type: "integer" },
            item: { type: "string" },
            description: { type: "string" },
            qty: { type: "number" },
            estimatedUnitCost: { type: "integer" },
            unitCostRange: { type: "string" },
            estimatedTotal: { type: "integer" },
            whereToBuy: { type: "string" },
            isLabor: { type: "boolean" },
            category: { type: "string" },
          },
          required: [
            "lineNumber",
            "item",
            "description",
            "qty",
            "estimatedUnitCost",
            "estimatedTotal",
            "whereToBuy",
            "category",
          ],
        },
      },
      costTotals: {
        type: "object",
        properties: {
          subtotal: { type: "integer" },
          laborTotal: { type: "integer" },
          contingencyPercent: { type: "integer" },
          contingency: { type: "integer" },
          grandTotal: { type: "integer" },
          budgetVersionTotal: { type: "integer" },
          budgetVersionNote: { type: "string" },
        },
        required: [
          "subtotal",
          "laborTotal",
          "contingencyPercent",
          "contingency",
          "grandTotal",
          "budgetVersionTotal",
          "budgetVersionNote",
        ],
      },
      phasingPlan: { type: "array", items: { type: "string" } },
      items: {
        type: "array",
        items: {
          type: "object",
          properties: {
            name: { type: "string" },
            estimatedCost: { type: "integer" },
            whereToBuy: { type: "string" },
            category: { type: "string" },
          },
          required: ["name", "estimatedCost", "whereToBuy", "category"],
        },
      },
      estimatedBudget: {
        type: "object",
        properties: {
          min: { type: "integer" },
          max: { type: "integer" },
          breakdown: { type: "string" },
        },
        required: ["min", "max", "breakdown"],
      },
      timelineHours: { type: "integer" },
      bangaloreTip: { type: "string" },
      noVacationNote: { type: "string" },
    },
    required: [
      "roomAnalysis",
      "primaryTheme",
      "designConcept",
      "alternativeTheme",
      "afterImageBrief",
      "roomStructure",
      "visionSummary",
      "designDirection",
      "colorPalette",
      "keyChanges",
      "assumptions",
      "costLineItems",
      "costTotals",
      "phasingPlan",
      "items",
      "estimatedBudget",
      "timelineHours",
      "bangaloreTip",
      "noVacationNote",
    ],
  },
};
